config/routes.rb
DelayedJobVisual::Engine.routes.draw do
  resources :delayed_jobs do
    member do
      put :rerun
    end
  end

  root to: 'delayed_jobs#index'
end

app/models/delayed_job.rb
class DelayedJob < ActiveRecord::Base

end

app/controllers/delayed_job_visual/application_controller.rb
module DelayedJobVisual
  class ApplicationController < ::ApplicationController
    protect_from_forgery with: :exception
  end
end

app/controllers/delayed_job_visual/delayed_jobs_controller.rb
require_dependency 'delayed_job_visual/application_controller'

module DelayedJobVisual
  class DelayedJobsController < ApplicationController

    load_and_authorize_resource

    def index
      @delayed_jobs = @delayed_jobs.order("run_at ASC")
    end # index

    def show
      
    end # show

    def destroy
      @delayed_job.destroy
    end # destroy

    def rerun
      @delayed_job.update_attributes(attempts: 0, last_error: nil, locked_at: nil, failed_at: nil, locked_by: nil, run_at: Time.now)
      redirect_to delayed_jobs_path
    end # rerun

  end
end

app/views/delayed_job_visual/delayed_jobs/_show.html.haml
.modal-dialog.modal-lg
  .modal-content
    .modal-header.text-center
      .bold.text-blue
        = "Delayed Job #{@delayed_job.id}"
        %a.close{data: {dismiss: 'modal'}} x
        
    .modal-body
      %fieldset
        %legend Job Type
        = @delayed_job.handler

      %fieldset
        %legend Error Info
        = @delayed_job.last_error

app/views/delayed_job_visual/delayed_jobs/destroy.js.haml
$("#job_#{@delayed_job.id}").fadeOut();

app/views/delayed_job_visual/delayed_jobs/index.html.haml
.row
  .col-sm-4
    - running_jobs_count = @delayed_jobs.select{|j| j.locked_at.present? && j.last_error.blank? }.count
    .well.text-center{class: ("label-success" if running_jobs_count > 0)}
      %h2.no-margin Running
      %h1.no-margin= running_jobs_count

  .col-sm-4
    - error_job_count = @delayed_jobs.select{|j| j.last_error.present?}.count
    .well.text-center{class: ("label-danger" if error_job_count > 0)}
      %h2.no-margin Error
      %h1.no-margin= error_job_count

  .col-sm-4
    - waiting_job_count = @delayed_jobs.select{|j| j.last_error.blank? && j.locked_at.blank? }.count
    .well.text-center{class: ("label-default" if waiting_job_count > 0) }
      %h2.no-margin Waiting
      %h1.no-margin= waiting_job_count





.table-responsive
  %table.table.table-condensed.table-striped.table-hover.table-fixed-header
    %thead
      %tr
        %th
        %th ID
        %th Queue
        %th Job Type
        %th Error
        %th{style: "width: 100px;"} Scheduled
        %th{style: "width: 100px;"} Errored at
        %th{style: "width: 150px;"}

    %tbody
      - if @delayed_jobs.length == 0
        %tr
          %th.text-center.middle{colspan: 500}
            There are no jobs waiting to run

      - else
        - @delayed_jobs.each do |job|
          %tr{id: "job_#{job.id}"}
            %td
              - if job.last_error.present?
                .label.label-danger Error
              - elsif job.locked_at.present?
                .label.label-success Running
              - else
                .label.label-default Waiting
            %td= job.id
            %td= job.queue.to_s.titleize
            %td= job.handler.truncate(125) if job.handler.present?
            %td= job.last_error.truncate(125) if job.last_error.present?
            %td.text-right{class: ('text-red' if Time.now > job.run_at)}
              = job.run_at.strftime("%b. %e, %Y<br>%l:%M:%S %P").html_safe
            %td.text-right= job.failed_at.strftime("%b. %e, %Y<br>%l:%M:%S %P").html_safe rescue '-'
            %td.middle.text-right
              .btn-group
                = link_to show_icon, job, remote: true, class: %w(btn btn-info)
                - if can?(:destroy, DelayedJob)
                  = link_to remove_icon, job, method: :delete, remote: true, data: {confirm: "Are you sure you want to remove this job from the job queue? This cannot be undone!"}, class: %w(btn btn-danger)
                - if can?(:rerun, job)
                  = link_to refresh_icon, rerun_delayed_job_path(job), method: :put, data: {confirm: "Are you sure you want to try and run this job again?"}, class: %w(btn btn-warning)


:javascript
  reload_page("#{delayed_jobs_path}", 4 * 60);
  $("#main-body-content").removeClass("container").addClass("container-fluid");

app/views/delayed_job_visual/delayed_jobs/show.js.haml
$("#modal-window").html("#{ j render partial: 'show' }");
$("#modal-window").modal();